pull_request_rules:
    - name: Automatic merge on approval
      conditions:
          - "#approved-reviews-by>=1"
          - label!=noautomerge
      actions:
          merge:
              method: squash
    - name: Auto-Label Testing
      conditions:
          - -draft
      actions:
          label:
              add:
                  - "Waiting for Testing"
    - name: Auto-Label Changes
      conditions:
          - changes-requested-reviews-by=thewilloftheshadow
      actions:
          label:
              add:
                  - "Waiting for Changes"
    - name: automatic merge for ImgBot pull requests
      conditions:
          - author=imgbot[bot]
      actions:
          label:
              remove:
                  - "Waiting for Changes"
                  - "Waiting for Testing"
          merge:
              method: squash
    - name: close stale pull request
      conditions:
          - base=main
          - -closed
          - updated-at<3 days ago
      actions:
          close:
              message: |
                  This pull request looks stale. Feel free to reopen it if you think it's a mistakke.
    - name: Autoreviewer
      conditions:
          - -closed
          - -draft
      actions:
          request_reviews:
              users:
                  - thewilloftheshadow
