pull_request_rules:
    - name: Automatic merge on approval
      conditions:
          - "#approved-reviews-by>=1"
      actions:
          merge:
              method: rebase
    - name: close stale pull request
      conditions:
          - base=main
          - -closed
          - updated-at<3 days ago
      actions:
          close:
              message: |
                  This pull request looks stale. Feel free to reopen it if you think it's a mistakke.
    - name: Autoreviewer
      conditions:
          - -closed
      actions:
          request_reviews:
              users:
                  - thewilloftheshadow
