name: Test

on:
    pull_request:
    push:
        branches:
            - main
    release:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install deps
              run: npm install
            #- name: Test
            #  run: npm run test
